### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by RikuTheFuffs** [brunomikoski/SpriteAuditor#13]
Hi, and thanks for the awesome tool! 

I noticed that the project is released under GNU GPL license. 
This means that if you want to distribute the application (I.E: a commercial game) that uses the tool  you have to make the source code of the application (read: "of the game") available. 

Is this inteded? 

If this tool is meant to be used in commercial games too, shouldn't it have a MIT license?

Thanks a lot for your attention,

Paolo

**Comment by brunomikoski** [comment]
Humm it's a good point, I really just want to avoid that someone would grab this tool and sell it not he asset store (It happens on the past with other assets I made :( )

I will investigate a little bit more what is the best license for this but be my guest and use it as you wish.

**Comment by brunomikoski** [comment]
I've fixed, let me know if this works for you:
https://github.com/badawe/SpriteAuditor/commit/14a4497840e0028d2c58b82c288c172b666044cf

**Comment by RikuTheFuffs** [comment]
Hi @badawe, sorry for my late reply. Yes, the new license seems good! Thanks for changing it :D
