### ISSUE TITLE
Can't find Tools/SpriteAuditor

### ISSUE THREAD

**Issue by AbishekJReuben** [brunomikoski/SpriteAuditor#17]
How do I open the SpriteAuditor window? It's not under Tools menu. I can find a greyed out Find Results of Selected Sprite button under Edit->SpriteAuditor menu, but northing under tools.
![image](https://user-images.githubusercontent.com/13975832/224173874-dbc60f38-69e9-4560-aa47-004803f6e132.png)
![image](https://user-images.githubusercontent.com/13975832/224173951-a41c69a8-9b05-4dc4-a03f-69e71c5b8037.png)
![image](https://user-images.githubusercontent.com/13975832/224173993-4c4fee69-e862-40c4-8234-b44e9793b78f.png)

**Comment by brunomikoski** [comment]
Sorry for the late answer, but it should be at ` Window/Analysis/Sprite Auditor`
